services:

  WildSiena\GoogleMapsBundle\:
    resource: '../src/'
    exclude:
      - '../src/WildSienaGoogleMapsBundle.php'
      - '../tests/'

  WildSiena\GoogleMapsBundle\Model\GoogleMap:
    autowire: true

  WildSiena\GoogleMapsBundle\Model\LoaderOptions:
    autowire: true

  WildSiena\GoogleMapsBundle\Model\MapOptions:
    autowire: false

  WildSiena\GoogleMapsBundle\Model\Marker:
    autowire: false

  WildSiena\GoogleMapsBundle\Model\LatLng:
    autowire: false

  WildSiena\GoogleMapsBundle\Twig\GoogleMapsExtension:
    autowire: true
    arguments:
      $stimulusHelper: '@stimulus.helper'
    tags: [twig.extension]